### ISSUE TITLE
Python para desktop com Tkinter

### ISSUE THREAD

**Issue by MauricioAlmeida** [lamenezes/python-intro#11]
Luiz,
sem querer me antecipar ao seu planejamento, pois vi que pretende falar de programação para desktop com Tkinter no último módulo, gostaria de saber qual o framework mais utilizado para o mundo desktop: é o Tkinter mesmo? Se for, existe algum jeito mais visual (tipo drag & drop) para montar as telas ou é tudo na base do código, via .grid mesmo?
Este final de semana comecei a brincar com isso e, ao mesmo tempo que achei interessante, fiquei imaginando que fazer um sistema todo montando as telas via código pode ser extremamente demorado.
Valeu

**Comment by lamenezes** [comment]
Os frameworks de interface gráfica mais utilizados para criar aplicações de grande porte são o PyQt, PyGTK e WxPython. Já trabalhei com PyGTK e brinquei com PyGTK, nunca vi nada do WxPython.

O PyGTK é baseado no GTK (Gnome ToolKit) e existe uma aplicação chamada Glade/GTK que cria telas usando drag & drop.

Eu sei que o PyQT tem uma IDE bem completa e permite criação de telas visualmente e, nessa parte, é parecido com o Eclipse/Netbeans.

Só uma dica que aprendi trabalhando com interface gráfica: use drag & drop para janelas simples, podem ter bastantes campos e widgets, mas a lógica tem que ser simples. Para telas complexas vale a pena criar telas na mão.
