### ISSUE TITLE
Sobre o uso de expressões regulares para separação de strings em Python

### ISSUE THREAD

**Issue by a-barone** [lamenezes/python-intro#13]
Tópico do stackoverflow:
http://stackoverflow.com/questions/13209288/python-split-string-based-on-regex

Mais sobre regex em Python:
http://regexone.com/references/python

**Comment by lamenezes** [comment]
A documentacão oficial da biblioteca de expressão regulares do Python é essa: https://docs.python.org/3/library/re.html

Na documentação são explicados os caracteres especiais, como mudar o funcionamento desses caracteres especiais para padrões diferentes e todas as funções de RE, como: search, match, split, find etc.

O livro Python Cookbook (Receitas Python), escrito por David Beazley e Brian Jones, tem ótimos exemplos/receitas de como executar tarefas em Python. Mais especificamente, em seu segundo capítulo, há ótimos exemplos de como trabalhar com expressões regulares. O código dessas receitas podem ser encontradas no github: https://github.com/dabeaz/python-cookbook/
