### ISSUE TITLE
Setar path no flask

### ISSUE THREAD

**Issue by brunojs02** [lamenezes/python-intro#14]
Tenho a seguinte estrutura na minha aplicação:
app:
      hello.py
      requirements.txt
      templates:
            assets(contendo os arquivos css e js):
            index.html

Acontece que quando eu subo essa aplicação no heroku, por exemplo, a aplicação não consegue enxergar o arquivo style.css que esta dentro da pasta assets.
O meu arquivo html que chama o style.css esta da seguinte forma:
<link `href="assets/bootstrap/css/style.css"` rel="stylesheet">
Sabem como posso estar setando o path corretamente?

**Comment by lamenezes** [comment]
Bruno,

Nunca mexi no flask (nem ao mesmo instalei e fiz um hello world), então não tenho conhecimento para te ajudar com isso. Você pode fazer essa pergunta para os usuários de python/flask nas listas de email:

Python Brasil: https://groups.google.com/forum/#!forum/python-brasil
Flask Brasil: https://groups.google.com/forum/#!forum/flask-brasil

**Comment by brunojs02** [comment]
Só por interesse, caso alguém precise, descobri como que faz...
Você precisa importar o modulo url_for do flask e quando for chamar o arquivo js/css... fica da seguinte forma dentro do href ou src, enfim...:
{{ url_for('static', filename='path/to/file') }}
obs: é preciso ter a pasta static na raiz do projeto!

**Comment by lamenezes** [comment]
solved
