### ISSUE TITLE
Plugins Vim

### ISSUE THREAD

**Issue by VictorRomano** [lamenezes/python-intro#16]
@lamenezes quais plugins você usa no seu vim para o desenvolvimento com Python?

**Comment by lucasmatheustesta** [comment]
hahaha.
me perguntei a mesma coisa ontem.
powerline, nerdtree, jedi, qual mais, fiquei interessado também rs.

2016-06-09 21:23 GMT-03:00 Victor Romano notifications@github.com:

> @lamenezes https://github.com/lamenezes quais plugins você usa no seu
> vim para o desenvolvimento com Python?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/opensanca/trilha-python/issues/16, or mute the thread
> https://github.com/notifications/unsubscribe/AGeUKOEfjZlXnn1CEjNpEaiByhbIg6Tlks5qKK5ogaJpZM4IyhrT
> .

## 

Lucas Matheus Testa.

_"Stay hungry. Stay foolish"_

**Comment by lamenezes** [comment]
opa!

eu deixo meu .vimrc e outros dotfiles em um repo no github: https://github.com/lamenezes/dotfiles

Mais especificamente eu uso esses:

Bundle 'gmarik/vundle'
"gerenciador de pacotes para o vim"

Bundle 'scrooloose/syntastic'
faz verificação de sintaxe para códigos de váris linguagens (Python, Javascript, PHP, etc.)

Bundle 'pangloss/vim-javascript'
Bundle 'vim-scripts/python.vim'
Bundle 'vim-scripts/django.vim'
Customizações para javascript, python e django

Bundle 'fholgado/minibufexpl.vim'
Exibe arquivos no buffer em abas

Bundle 'plasticboy/vim-markdown'
Ajuda a visualizar arquivos markdown

Bundle 'Lokaltog/powerline'
Ruler mais bonitinha

Bundle 'sjl/gundo.vim'
Dá uma interface bonitinha dos históricos de mudanças de cada arquivo

Bundle 'davidhalter/jedi-vim'
Auto completar mágico

Bundle 'wincent/Command-T'
Meu plugin favorito do momento: permite buscar arquivos nos repositórios de uma maneira `fuzzy`
