### ISSUE TITLE
Selenium problem

### ISSUE THREAD

**Issue by lucasmatheustesta** [lamenezes/python-intro#17]
Fala Luiz, blz ?
Cara sei que você não entrou nesse assunto ainda, mas tem ideia por quê quando eu tento rodar o selenium ele da problema ?

Segue em anexo prints.

Muito Obrigado
![captura de tela de 2016-06-12 10-20-22](https://cloud.githubusercontent.com/assets/6788136/15991372/7b37356e-3087-11e6-91ca-6d6eaffa97a9.png)
![captura de tela de 2016-06-12 10-20-28](https://cloud.githubusercontent.com/assets/6788136/15991374/842c5d66-3087-11e6-94f1-432201b5a28b.png)

**Comment by lamenezes** [comment]
@lucasmatheustesta você testou esse exemplo sem passar o binary para o construtor de Firefox? Assim:

``` py
def setUp(self):
    self.browser = webdriver.Firefox()
```

Pelo o que lembro de usar o selenium nunca precisei passar um binary.

**Comment by lamenezes** [comment]
solved

**Comment by lamenezes** [comment]
@lucasmatheustesta achei o problema: selenium não está funcionando com o Firefox 47 e é necessário fazer um workaround para funcionar, mais informações aqui: http://stackoverflow.com/questions/37761668/cant-open-browser-with-selenium-after-firefox-update
