### ISSUE TITLE
Erro ao instalar ipython notebook no Mint e algumas versões do ubuntu

### ISSUE THREAD

**Issue by lamenezes** [lamenezes/python-intro#2]
O erro acontece ao instalar a dependência **pyzmq** (biblioteca de messageria distribuída). Esse tipo de erro geralmente acontece pois o computador não possui os cabeçalhos do código-fonte dessas dependências.

Geralmente  é necessário instalar pelo apt-get algum pacote como python3.5**-dev** python3.4**-dev** python**-dev**

**Comment by lamenezes** [comment]
Esse comando pode resolver:

```
sudo apt-get install libzmq3-dev
```

e/ou esse:

```
sudo apt-get install libzmq-dev
```

e/ou esse:

```
sudo apt-get install --reinstall libzmq3 libzmq3-dev
```

**Comment by ghost** [comment]
Pessoal, tudo bem?
Tenho interesse em usar o Jupyter no curso, mas ainda não consegui instalar. 

Ele retorna esse erro:
`(env) usuario@usuario-Dell-System-XPS-L502X ~/env/env $ jupyter notebook
Traceback (most recent call last):
  File "/home/usuario/env/env/env/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 9, in <module>
    import sqlite3
  File "/usr/local/lib/python3.5/sqlite3/**init**.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
**ImportError: No module named '_sqlite3'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usuario/env/env/env/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/usuario/env/env/env/lib/python3.5/site-packages/notebook/notebookapp.py", line 61, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/usuario/env/env/env/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
**ImportError: No module named 'pysqlite2'**
`
Pesquisei por esses erros no Stackoverflow e testei algumas coisas que vi, como instalar o _libsqlite3-dev_ (instala sem erros), tentei _get update_ , tentei atualizar o pip e nada.
(não sei ao certo o que o install _libzmq3-dev_ que @lamenezes postou mas tbm tentei)

Se alguém tiver uma luz do que possa fazer e puder compartilhar, agradeço.

Obrigada!

**Comment by lamenezes** [comment]
Oi, Gabriele.

Você poderia verificar a versão do Python do seu virtualenv? Use o seguinte comando:

```
(env) $ python --version
```

Como os erros dizem o problema está no SQLite, parece que tem alguma treta entre o sqlite2 e sqlite3. Você pode rodar o comando a seguir e mostrar a saída para sabermos quais versões do sqlite estão instaladas na sua máquina?

```
(env) $ dpkg -l *sqlite*
```

A Juliana, que também está fazendo o curso, também estava com esse erro no ubuntu 14.04 dela. Ela formatou e instalou Ubuntu 16.04 e tudo instalou sem problemas.

**Comment by ghost** [comment]
Oi Luis, obrigada pela resposta.

A versão é a
`Python 3.5.1`

`(env) $ dpkg -l *sqlite*` retorna
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  libqt4-sql-sql <none>       <none>       (no description available)
ii  libqt5sql5-sql 5.2.1+dfsg-1 amd64        Qt 5 SQLite 3 database driver
un  librdf-storage <none>       <none>       (no description available)
ii  libsqlite3-0:a 3.8.2-1ubunt amd64        SQLite 3 shared library
ii  libsqlite3-0:i 3.8.2-1ubunt i386         SQLite 3 shared library
ii  libsqlite3-dev 3.8.2-1ubunt amd64        SQLite 3 development files
un  libsqliteodbc  <none>       <none>       (no description available)
ii  sqlite3        3.8.2-1ubunt amd64        Command line interface for SQLite
un  sqlite3-doc    <none>       <none>       (no description available)

Estou usando o Mint 17.3, se com essas infos você imaginar o que posso fazer, seria lindo. Se não vou tentar trocar o Mint pelo Ubuntu mesmo.

Obrigada!

**Comment by lamenezes** [comment]
Você instalou o `pysqlite` pelo pip no seu virtualenv? Se não:
`pip install pysqlite`
Depois tente rodar o jupyter notebook

Se não der certo não sei como resolver :disappointed:

**Comment by ghost** [comment]
Mesmo assim não deu :(
Acabei instalando o Ubuntu 16.04, rodou sem erro :)

Obrigada por isso! Abs.

**Comment by lamenezes** [comment]
@gabrielelandim que chato que você teve de formatar :disappointed: 

Vou fechar aqui a issue, aparentemente a solução é não usar essa versão do mint
