### ISSUE TITLE
Aulas Finais - Trilha de Python

### ISSUE THREAD

**Issue by MauricioAlmeida** [lamenezes/python-intro#25]
Pessoal (em especial Luiz),

sobre as duas próximas aulas, lembro bem que na quinta-feira será a Mariana falando sobre Machine Learning, mas não consigo lembrar o assunto da aula de terça-feira. Alguém pode me relembrar?

Grato

**Comment by lamenezes** [comment]
Programação funcional em Python com o Alan Jorge

**Comment by MauricioAlmeida** [comment]
Obrigado, Luiz. A memória anda fraca!!!

Abraço
