### ISSUE TITLE
Diferença entre o Bottle e Flask

### ISSUE THREAD

**Issue by brunojs02** [lamenezes/python-intro#3]
Alguém saberia citar as grandes diferenças entre bottle e flask?

**Comment by lamenezes** [comment]
Ambos são microframeworks Python e funcionam perfeitamente.

O Bottle é o papai conservador do Flask. Como são pai e filho a sintaxe, nomes de funções e funcionamento são **extremamente** parecidos, o que muda é: como são implementados e popularidade.

O [Bottle](http://bottlepy.org/) é um microframework até em sua criação: é todo escrito em apenas um arquivo e usa somente dependências da biblioteca padrão do Python.
É uma ótima escolha para fazer aplicações web para rodar em embarcados, servidores antigos, projetos que já possuem muitas dependências e você, como desenvolvedor, não quer aumentá-las ou para casos que exista restrições/dificuldades de instalação de bibliotecas.

[Flask](http://flask.pocoo.org/) começou como um fork do Bottle, pois um de seus core developers achava (com razão) de que o Bottle era muito limitante, pois não era possível usar bibliotecas terceiras o que dificultava a implementação e integração com outras ferramentas importantes para desenvolver aplicações web.

Sem essa limitação o Flask bombou e atualmente ele é o microframework mais utilizado no mundo Python. Flask possui muitas extensões feitas pela comunidade Python, tantas que é possível usar o Flask como um framework full stack assim como o django (pessoalmente eu não gosto de usar o Flask para isso, mas tem pessoas que usam e funciona).
