### ISSUE TITLE
Como instalar e usar Git no Windows - Referencias

### ISSUE THREAD

**Issue by cristofersousa** [lamenezes/python-intro#5]
#### Segue material de referencias para instalar e usar Git/Github no Windows.
- [Utilizando o GIT via command line Windows](http://imasters.com.br/desenvolvimento/utilizando-o-git-via-command-line-windows/?trace=1519021197&source=single)
- [Usando Git para Windows](http://blog.dmatoso.com/2011/09/git-no-windows-github/)
- [Como usar Git no Windows](http://mauriciodeamorim.com.br/2009/01/06/como-usar-git-no-windows/)
- [Github: descomplicando o git no windows](http://lorindo.com/github-descomplicando-o-git-no-windows/)
- [Instalando o Git e configurando Github no Windows.](http://gabsferreira.com/instalando-o-git-e-configurando-github/)

**Comment by lamenezes** [comment]
acho que esses guias podem ficar junto do material do treinamento de git no treinamento-git/README.md, o que você acha?

**Comment by cristofersousa** [comment]
Justo!
